test(k8s): 优化核心测试脚本的错误处理和稳定性
- 移除了不必要的 set -e 命令
- 在获取 cookie 和用户信息的 curl 请求后添加了错误检查
- 在获取用户信息失败时输出错误消息并退出
- 在获取 cookie时增加了文件存在性检查
- 在 GitHub Actions 中增加了 5秒的等待时间，以提高测试的稳定性

diff --git a/.github/workflows/e2e_kubernetes.yml b/.github/workflows/e2e_kubernetes.yml
--- a/.github/workflows/e2e_kubernetes.yml
+++ b/.github/workflows/e2e_kubernetes.yml
@@ -75,7 +75,13 @@ jobs:
 
       - name: Start Lubricant Test
         run: |
-          set -e 
+          # set -e 
           lubricant_pod=$(kubectl get pods -n lubricant | awk '/lubricant-core/ {print $1}')
           bash scripts/function/wait_pod.sh $lubricant_pod lubricant
+          sleep 5
           kubectl exec nginx -- bash /root/k8s/core-test.sh
+          if [ $? -ne 0 ]; then
+            echo "TestFailed: Stdout Information:"
+            kubectl describe pod $lubricant_pod -n lubricant
+            exit 1
+          fi
